name: Test
run-name: ${{ github.actor }} is testing
on:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  Clone-install-test:
    name: Test on PHP ${{ matrix.php-versions }} and ORM ${{ matrix.doctrine-orm-version }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        doctrine-orm-version:
          - 2.15.5
          - 2.16.0
        php-versions:
          - 7.3
#          - 7.4
#          - 8.0
#          - 8.1
#          - 8.2
#          - 8.3
          - 8.4
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Remove composer.lock
        run: rm composer.lock

      - name: Install Composer dependencies and doctrine version
        run: composer require doctrine/orm:${{ matrix.doctrine-orm-version }} --no-progress --prefer-dist --optimize-autoloader

      - name: Run tests
        run: vendor/bin/phpunit tests
