name: Test
run-name: ${{ github.actor }} is testing
on:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  Clone-install-test:
    name: Test on PHP ${{ matrix.php-versions }} ${{ matrix.composer-update-param  }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        composer-update-param: ['', '--prefer-lowest']
        php-versions:
          - 5.6
          - 7.0
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Remove composer.lock
        run: rm composer.lock

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Downgrade to lowest Composer versions
        if: ${{ matrix.composer-update-param }}
        run: composer update ${{ matrix.composer-update-param }} --no-progress --prefer-dist --optimize-autoloader

      - name: Run tests
        run: vendor/bin/phpunit tests
